spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  datasource:
#    url: jdbc:sqlserver://localhost;databaseName=demo_board;trustServerCertificate=true;encrypt=true;
#    username: sa
#    password: rudnf12dnjf
logging:
  config: classpath:log4j2.xml
debug: false
server:
  port: 8080
  servlet:
    context-path: /